plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - LICENSE.md
  - ISSUE_TEMPLATE.md
  - examples
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-hacker
show_downloads: [true]
toc:
  enabled: true
  h_min: 1
  h_max: 3
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

exclude:
  - README.md
  - Makefile
  - CMakeLists.txt
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - build
  - src
  - libuv
  - coroutine-built
  - pthreads4w
  - .github
  - valgrind.supp
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
